# Generated by Django 2.0.5 on 2018-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCitys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'job_citys',
                'managed': False,
            },
        ),
    ]
