# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_auto_20180720_1020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobmsg',
            table='job_msg_final',
        ),
    ]
